### ISSUE TITLE
Folder Structure

### ISSUE THREAD

**Issue by frknasir** [CJIDNG/udeme-pod#1]
Folder Structure
================

Goal
-----------

- Clear feature ownership
- Module usage predictability (refactoring, maintenance, separate what's shared from what is not, avoids huge directories of modules that will be hard to reuse)

Basic Principle
------------

The file structure should map directly to the route hierarchy, which will then map
directly to the UI hierarchy.

say, all folders are either a "generic" or a "feature" folder, we have 
one `feature` folder to many `generic` folders

Examples of "feature" folders:

- Users
- Projects
- Admin

Examples of "generic" folders:

- components
- helpers
- stores
- actions

Given this route config:

```js
var routes = (
  <Route name="App">
    <Route name="Admin">
      <Route name="Users"/>
      <Route name="Projects"/>
      <Route name="Agency"/>
      <Route name="Ministry"/>
      <Route name="State"/>
      <Route name="LocalGovernment"/>
    </Route>
    <Route name="Main">
      <Route name="Projects"/>
      <Route name="User"/>
    </Route>
  </Route>
);
```

Our directories would look like this:

```
app
└── screens
    └── App
        └── screens
            ├── Admin
            │   └── screens
            │       ├── Users
            │       └── Projects
            │       └── Agencies
            │       └── Ministries
            │       └── States
            │       └── LocalGovernments
            └── Main
                └── screens
                    └── Projects
                    └── User
```

Each of these screens should have an `index.js` file, which will be the file
that handles the entry into the screen, also known as a "Route Handler"
in react router. We should also have some top-level application bootstrapping at the root:  `config/routes.js`.

```
app
├── config
│   └── routes.js
├── screens
│   └── App
│       ├── screens
│       │   ├── Admin
│       │   │   ├── screens
│       │   │   │   ├── Users
│       │   │   │   │   └── index.js
│       │   │   │   └── Projects
│       │   │   │       └── index.js
|       |   |   |   └── Agencies
|       |   |   |       └── index.js
|       |   |   |   └── Ministries
|       |   |   |       └── index.js
|       |   |   |   └── States
|       |   |   |       └── index.js
|       |   |   |   └── LocalGovernments
|       |   |   |       └── index.js
│       │   │   └── index.js
│       │   └── Main
│       │       ├── screens
│       │       │   └── Projects
│       │       │       └── index.js
|       |       |   └── Users
|       |       |       └── index.js
│       │       └── index.js
│       └── index.js
└── index.js
```

With this structure, each screen has its own directory to hold its
modules. In other words, we've introduced "scope" into our application
file structure.

Each will have a `components` directory.

```
app
├── config
│   └── routes.js
├── screens
│   └── App
│       ├── components
│       ├── screens
│       │   ├── Admin
│       │   │   ├── components
│       │   │   ├── screens
│       │   │   │   ├── Users
│       │   |   │       ├── components
│       │   │   │   │   └── index.js
│       │   │   │   └── Projects
│       │   |   │       ├── components
│       │   │   │       └── index.js
|       |   |   |   └── Agencies
│       │   |   │       ├── components
|       |   |   |       └── index.js
|       |   |   |   └── Ministries
│       │   |   │       ├── components
|       |   |   |       └── index.js
|       |   |   |   └── States
│       │   |   │       ├── components
|       |   |   |       └── index.js
|       |   |   |   └── LocalGovernments
│       │   |   │       ├── components
|       |   |   |       └── index.js
│       │   │   └── index.js
│       │   └── Main
│       │       ├── components
│       │       ├── screens
│       │       │   └── Projects
│       │       │       ├── components
│       │       │       └── index.js
|       |       |   └── Users
│       │       │       ├── components
|       |       |       └── index.js
│       │       └── index.js
│       └── index.js
└── index.js
```

These components are used *only in the current screen*, not even the
child screens. So what about when you've got some shared components
between screens?

### Shared Modules

Every screen also has a "shared" generic directory. If its children
share any components with each other or the parent, we put the shared
code in "shared". Here is our growing app with some new shared, and not
shared modules.

```
app
├── config
│   └── routes.js
├── screens
│   └── App
│       ├── components
│       ├── screens
│       │   ├── Admin
│       │   │   ├── components
│       │   │   ├── screens
│       │   │   │   ├── Users
│       │       │       ├── components
│       │   │   │   │   ├── stores
│       │   │   │   │   │   └── UsersStore.js
│       │   │   │   │   └── index.js
│       │   │   │   └── Projects
│       │       │       ├── components
│       │   │   │   │   ├── stores
│       │   │   │   │   │   └── ProjectsStore.js
│       │   │   │       └── index.js
|       |   |   |   └── Agencies
│       │       │       ├── components
│       │   │   │   │   ├── stores
│       │   │   │   │   │   └── AgenciesStore.js
|       |   |   |       └── index.js
|       |   |   |   └── Ministries
│       │       │       ├── components
│       │   │   │   │   ├── stores
│       │   │   │   │   │   └── MinistriesStore.js
|       |   |   |       └── index.js
|       |   |   |   └── States
│       │       │       ├── components
│       │   │   │   │   ├── stores
│       │   │   │   │   │   └── StatesStore.js
|       |   |   |       └── index.js
|       |   |   |   └── LocalGovernments
│       │       │       ├── components
│       │   │   │   │   ├── stores
│       │   │   │   │   │   └── LocalGovernmentsStore.js
|       |   |   |       └── index.js
│       │   │   ├── shared
│       │   │   │   └── stores
│       │   │   │       ├── ProjectsStore.js
│       │   │   │       └── UsersStore.js
│       │   │  └── index.js
│       │   └── Main
│       │   |   ├── components
│       │   |   ├── screens
│       │   |    │   └── Projects
│       │   |    │       ├── components
│       │   |    │   │   ├── stores
│       │   |    │   │   │   └── ProjectsStore.js
│       │   |    │       └── index.js
|       |   |    |   └── Users
│       │   |    │       ├── components
│       │   |    │   │   ├── stores
│       │   |    │   │   │   └── UsersStore.js
|       |   |    |       └── index.js
│       └── Shared
│          └── components
│              └── Avatar.js
│              └── Icon.js
│                  └── index.js
├── shared
│   └── util
│       └── createStore.js
└── index.js
```

Note `Admin/shared`; `Users` , `Projects`, `Agencies` etc can both access the shared
stores. Additionally, every screen in the app can use `Avatar.js` and `Icon.js`.

We put shared components in the nearest `shared` directory possible and
move it toward the root as needed.

<!--### Shared module resolution

The way modules in CommonJS are resolved is pretty straightforward in
practice: its all relative from the current file.

There is one piece of "magic" in the way modules resolve. When you do a
non-relative require like `require('moment')` the resolver will first
try to find it in `node_modules/moment`. If its not there, it will look
in `../node_modules/moment`, and on up the tree until it finds it.

We've made it so that `shared` resolves the same way with webpack
`modulesDirectories`. This way you don't have to
`require('../../../../../../../../../../shared/Avatar')` you can simply
do `require('components/Avatar')` no matter where you are.

### Tests

Tests live next to the modules they test. Tests for
`shared/util/createStore.js` live in `shared/util/__tests__/createStore.test.js`.

Now our app has a bunch of `__tests__` directories:

```
app
├── __tests__
├── config
│   └── routes.js
├── screens
│   └── App
│       ├── components
│       │   ├── __tests__
│       │   │   └── AppView.test.js
│       │   └── AppView.js

... etc.

├── shared
│   └── util
│       ├── __tests__
│       │   └── createStore.test.js
│       └── createStore.js
└── index.js
``` -->

**Comment by frknasir** [comment]
What do you think of this approach??? @OdunayoOkebunmi

**Comment by OdunayoOkebunmi** [comment]
Awesome! It looks good. What about integrating it with redux?

**Comment by frknasir** [comment]
how do you mean?

**Comment by OdunayoOkebunmi** [comment]
For redux, we'll need the `actions`, `reducers`, `store` folders. Since each feature has its own `store`, I'm guessing they would also have their own `reducers` and `actions`. Is that correct?

**Comment by frknasir** [comment]
true. so this is the basic folder structure...the idea is that you will build on it as you work on the project
