### ISSUE TITLE
Why Context + Hooks?

### ISSUE THREAD

**Issue by frknasir** [CJIDNG/udeme-pod#9]
Investigate why we should use context + hooks instead of redux for state management and document your findings here.

**Comment by OdunayoOkebunmi** [comment]
Basically, context provides a way of passing data from one component to the other without passing props manually at every level. Context is mainly used when you want simple state management or when you want to avoid `props drilling`
In context, you won't have the advantages that come with Redux:
- time-traveling debugger
- middleware API like redux-thunk
- React bindings that prevent unnecessary renders

But if the major reason you need state management is to handle the way props are being passed, then Context is the go-to.
